pipeline {
    agent any

    environment {
        REGISTRY = "maaryii"
        IMAGE_NAME = "test-image"
    }

    stages {

        // Stage 1: Checkout SCM
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // Stage 2: Build Maven Project
        stage('Build Maven Project') {
            steps {
                // Run Maven inside project directory where pom.xml exists
                dir('jenkins/task3/Jenkins_App') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        // Stage 3: Build Docker Image
        stage('Build Docker Image') {
            steps {
                script {

