---
- name: Configure a web server
  hosts: node1
  become: yes
  tasks:
    - name: Install Nginx
      command: dnf install -y nginx

    - name: Enable and start Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Customize the default web page
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
          <head><title>Welcome to My Automated Web Server</title></head>
          <body style="font-family: sans-serif; text-align: center; margin-top: 10%;">
            <h1>Hello from Ansible!</h1>
            <p>This web page was deployed automatically 🚀</p>
          </body>
          </html>

